### ISSUE TITLE
Cache links broken in suburls

### ISSUE THREAD

**Issue by designermonkey** [Circa75/dropplets#332]
When viewing a category page for example, images are looked up from `./cache/image.png` for example.

This needs fixing in PHP to remove the `./` from the beginning in favour of `/`. I've temporarily fixed it with the following htaccess rule.

```
RewriteRule (.*)/cache/(.*) /cache/$2 [L]
```

**Comment by dimo414** [comment]
Rewriting requests from `./cache` to `/cache` is problematic for anyone who doesn't have Dropplets installed in their site root.

**Comment by chicknwitnoname** [comment]
The fix I implemented for this issue was to edit `index.php` directly by inserting `?filename=`.

Look for the line following `// Get the post category link.`

Change from:
`$post_category_link = $blog_url.'category/'.urlencode(trim(strtolower($post_category)));`
Change to:
`$post_category_link = $blog_url.'?filename=category/'.urlencode(trim(strtolower($post_category)));`
