### ISSUE TITLE
How to install Dropplets on Google App Engine?

### ISSUE THREAD

**Issue by hoangloi** [Circa75/dropplets#389]
Hi all,
I want install Dropplets on *Google App Engine*, is it ok?

how to config file *app.Yaml*? or enable *mode_rewrite* on app?

I was setup Dropplets as use manual *config.php* and *htaccess* from my local. it's running. but it can't publish md post. I think I need your help when install it on GAE.

**Comment by benlk** [comment]
You'll need to set the runtime in `app.yaml` to php55: https://cloud.google.com/appengine/docs/php/

GAE doesn't do `mod_rewrite` because it's not using Apache, but this help page may be of use to you: https://cloud.google.com/appengine/docs/php/config/mod_rewrite

I haven't used GAE, so I don't know anything about this problem. I'm just Googling for solutions. As far as I know, you're the first GAE user.

**Comment by hoangloi** [comment]
Thanks Benlk. I'm running on GAE. just try run on it. but we will manual update step from config, htaccess and upload post md ... 
I just run for learn. but dropplets is not work on GAE. because we don't work anything with a system "read-only" as GAE. 

THANKS again.

**Comment by rt7651** [comment]
Any solution to install on Openshift

**Comment by hoangloi** [comment]
Hi @rt7651 with my experience. on Openshift you need cmod to config.php and posts folder 755. everything ok for me.
